POST http://127.0.0.1:8000/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}


###


POST http://127.0.0.1:8000/signup
Content-Type: application/json

{
    "username": "admin1",
    "password": "admin1"
}


###


GET http://127.0.0.1:8000/test_token
Content-Type: application/json
Authorization: Token 209dc5c9e312cd19b04f5ce825e499b94ec863178

{}
