# Generated by Django 5.0.3 on 2024-05-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0002_appointment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default="2000-01-01T00:00:00Z"),
            preserve_default=False,
        ),
    ]
